### ISSUE TITLE
Spam Fees [RFC]

### ISSUE THREAD

**Issue by nicoduclare** [wieldprotocol/universe#5]
## Abstract

The “Simple Mail Transfer Protocol” (SMTP), one of the oldest mass-adopted decentralized internet communication protocol, has had a history of [SPAM issues and proposed solutions](https://blog.lopp.net/death-of-decentralized-email/). With a high server cost imposed on the receiver to filter and process large quantity of mails come the centralization in the hands of tech giants capable of supporting such endeavor.

## Problem

The BEB protocol make use of public blockchain addresses and decentralized top-level domains (dTLDs) such as bebverse.eth. This has led to an increased potential for spam, as evidenced by the current challenges faced by the Simple Mail Transfer Protocol (SMTP).

## Proposal

A “SPAM” fee is a proposal to dissuade high-volume low-quality senders. With the unit economic in favor of the receiver, this learns from the lessons of SMTP in order to preserve decentralization in favor of independent node operators.

## Goal
A dynamic, standardized, and chain-agnostic fee retrieval and verification process capable of communicating to all peers.

### Option 1
 - A [BebApprover Smart Contract](https://github.com/bebverse/dimension/files/10515986/BebApprover.sol.txt) by @vrypan, [see his comment for details](https://github.com/bebverse/dimension/issues/5#issuecomment-1406065871).
### Option 2
 - Reference the spam fee from our [decentralized metadata](https://github.com/bebverse/dimension/issues/1), then add metadata in an onchain transaction referencing the message hash that needs to be sent to the dimension owner. When sending a message with the transaction, the dimension queries an Ethereum node to confirm the spam fee was paid.

**Comment by vrypan** [comment]
This is a sample BEBApprover contract that actually compiles.
[BebApprover.sol.txt](https://github.com/bebverse/dimension/files/10515986/BebApprover.sol.txt)

Being able to set special handling (zero fees in this implementation, but it could be more complex) for owners of specific tokens, makes a number of use cases easy to support. For example, you could get approvals for free in the use cases bellow, just by setting the contract address and limits in setSpecial():

- NFT communities: Owning a specific NFT (balanceOf>0)
- DAOs: owning an amount of a DAO's tokens, for example 100 UNI
- DeFi: Staking at least X protocol tokens
- Companies/Universities/Organisations: owners of the company-issued/controlled NFT/token
- Third party whitelists or credibility scores: Instead of a ERC-20 or ERC-721, any contract that provides a balanceOf() can be used. For example, a smart contract that acts as an oracle and scores users based on their discord activity and balanceOf() returns the user's score.

**Comment by ethjcdenton** [comment]
Thank you @vrypan, I put down a BEBApproval as option 1 for implementing spam fees.

I wonder if there's an simplier way to have spam fees, I put down the following as option 2: Metadata in an onchain transaction referencing a message hash. When sending a message with the transaction, the dimension queries an Ethereum node to confirm the spam fee was paid.
